services:
  postgres:
    container_name: dt_postgres
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: dentaltech-db
      POSTGRES_USER: hygorp
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: dt_rabbitmq
    image: rabbitmq:3.9
    environment:
      RABBITMQ_DEFAULT_USER: hygorp
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data: